import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/styles/main.scss";
import Provider from "@/components/Provider";

const geistSans = Inter({
  variable: "--font-inter",
  style: ["normal"],
  subsets: ["latin", "cyrillic"],
  weight: ["400", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang='en'>
        <body className={`${geistSans.variable}  antialiased`}>{children}</body>
      </html>
    </Provider>
  );
}
